eureka:
  client:
    register-with-eureka: true
    fetch-registry : true
    serviceUrl :
      defaultZone : http://localhost:8761/eureka/
  instance:
      hostname: localhost
      
microservice:
  springboot-API-paymentservice:
    endpoints:
      endpoint:
        uri: http://PAYMENT-SERVICE/payment/save-payment
  springboot-API-orderservice:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/save-order      
